#:schema node_modules/wrangler/config-schema.json
name = "rdrx"
main = "src/index.ts"
compatibility_date = "2024-12-05"
compatibility_flags = ["nodejs_compat"]

# Static Directory
[assets]
directory = "./static"
binding = "STATIC"

# Vars
[vars]
FRONTEND_URL = "https://okx.run"
SHORT_DOMAIN = "okx.run"
FROM_EMAIL = "no-reply@go.rdrx.co"
R2_URL = "https://okx.run/files"
DISABLE_SIGNUPS = "true"

# Workers Logs
[observability]
enabled = true

[triggers]
# daily cron trigger for cronDelete
crons = ["0 0 * * *"]

[[d1_databases]]
binding = "DB"
database_name = "rdrx"
database_id = "8dab09a2-61b6-40f4-8f19-99c1a1ee8271"

[[kv_namespaces]]
binding = "RDRX_KV"
id = "53565900af374a23906a2227af2725ee"
preview_id = "0c3ffd554cbb4401b00c221424c6d023"

[[r2_buckets]]
binding = "R2_RDRX"
bucket_name = "rdrx"
